# Change prefix from Ctrl+b to Ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Switch panes using Vim movements after the prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Split panes vertically using |
bind | split-window -h -c "#{pane_current_path}"

# Split panes horizontally using -
bind - split-window -v -c "#{pane_current_path}"

# Unbind default split keys
unbind '"'
unbind %
